<a href="https://colab.research.google.com/github/IrisCheon/NLP-practice/blob/main/Customer_Support_Discourse_Analysis_on_Twitter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Customer Support Tweet Topic Modeling

This project explores topic modeling on customer support tweets using TF-IDF and NMF. The initial goal was to identify semantic issue-related topics from customer complaints, while also examining how traditional bag-of-words topic modeling behaves on short and noisy conversational text.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("thoughtvector/customer-support-on-twitter")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/thoughtvector/customer-support-on-twitter/10.archive...

100%|██████████| 169M/169M [00:01<00:00, 173MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/thoughtvector/customer-support-on-twitter/versions/10

In [4]:
print(os.listdir(path))

['sample.csv', 'twcs']

In [19]:
!file {path}/twcs

/root/.cache/kagglehub/datasets/thoughtvector/customer-support-on-twitter/versions/10/twcs: directory

#■ 데이터 확인

In [20]:
df = pd.read_csv(f"{path}/twcs/twcs.csv")
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2811774 entries, 0 to 2811773
Data columns (total 7 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tweet_id                 int64
 1   author_id                object
 2   inbound                  bool
 3   created_at               object
 4   text                     object
 5   response_tweet_id        object
 6   in_response_to_tweet_id  float64
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 131.4+ MB

In [23]:
df.columns

Index(['tweet_id', 'author_id', 'inbound', 'created_at', 'text',
       'response_tweet_id', 'in_response_to_tweet_id'],
      dtype='object')

In [24]:
df.isnull().sum()

tweet_id                         0
author_id                        0
inbound                          0
created_at                       0
text                             0
response_tweet_id          1040629
in_response_to_tweet_id     794335
dtype: int64

In [25]:
customers = df[df["inbound"] == True].copy()
brands = df[df["inbound"] == False].copy()

In [26]:
customer_sample = customers.sample(30000, random_state = 42)
brand_sample = brands.sample(30000, random_state = 42)

In [27]:
import re

In [28]:
def clean_tweet(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [29]:
customer_sample["clean_text"] = customer_sample["text"].apply(clean_tweet)

In [31]:
customer_sample["word_count"] = customer_sample["clean_text"].str.split().str.len()
customer_sample = customer_sample[customer_sample["word_count"]>=5].copy()

customer_sample.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,clean_text,word_count
26861,34581,123491,True,Wed Nov 01 14:03:55 +0000 2017,@AppleSupport Basically for a chat to be opene...,34582,34579.0,basically for a chat to be opened from call lo...,23
211386,246537,174558,True,Thu Oct 05 14:08:30 +0000 2017,@AppleSupport iOS 11.02 and Watchos4.0: No ico...,"246536,246538",NaN,ios and watchos no icon for twitter notificati...,21
1225222,1351215,435088,True,Mon Oct 16 13:33:22 +0000 2017,@ATVIAssist Hi there! If I buy Call of Duty WW...,1351214,NaN,hi there if i buy call of duty wwii on steam t...,22
194583,228814,170570,True,Thu Oct 05 08:01:11 +0000 2017,Hi @Safaricom_Care why can't I pay my my Dstv ...,228812,NaN,hi why can t i pay my my dstv texts says the o...,15
1321593,1456209,457998,True,Thu Nov 02 18:45:26 +0000 2017,trying to buy my kid nibling a keyboard for an...,1456208,NaN,trying to buy my kid nibling a keyboard for an...,23

#■ TF-IDF + NMF

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

In [33]:
vectorizer = TfidfVectorizer(
    stop_words = "english",
    max_df = 0.8,
    min_df = 10,
    max_features = 5000,
    ngram_range = (1,2)
)

X = vectorizer.fit_transform(customer_sample["clean_text"])

In [35]:
n_topics = 6

nmf = NMF(
    n_components = n_topics,
    random_state = 42,
    max_iter = 300,
    init = "nndsvda"
)

W = nmf.fit_transform(X)    # 각 문서가 어떤 토픽을 갖는지?
H = nmf.components_     # 각 토픽이 어떤 단어를 중요하게 갖는지?

In [36]:
feature_names = vectorizer.get_feature_names_out()

def display_topics(model, feature_names, n_top_words = 10):
    for topic_idx, topic in enumerate(model.components_):
        top_indices = topic.argsort()[::-1][:n_top_words]
        top_words = [feature_names[i] for i in top_indices]

        print(f"\nTopic {topic_idx}")
        print(", ".join(top_words))

display_topics(nmf, feature_names, 15)

Topic 0
time, phone, don, ve, amp, order, like, app, fix, new, going, flight, day, update, today

Topic 1
service, customer, customer service, worst, worst customer, terrible, care, great, poor, customer care, today, bad, experience, horrible, good

Topic 2
thanks, hi, dm, reply, ok, great, ll, thanks help, thanks reply, ok thanks, response, check, sure, good, flight

Topic 3
help, need, need help, account, dm, hi, email, hey, trying, thanks help, number, asap, sent, hello, help account

Topic 4
thank, dm, sent, reply, sent dm, appreciate, response, flight, great, yes, thank help, okay, hi, ll, did

Topic 5
just, got, just got, just want, want, sent, just sent, dm, bought, know, wanted, just bought, people, ve just, just wanted


- Topic 0
time, phone, don, ve, amp, order, like, app, fix, new, going, flight, day, update, today
    - 시간 관련

- Topic 1
service, customer, customer service, worst, worst customer, terrible, care, great, poor, customer care, today, bad, experience, horrible, good
    - 불만

- Topic 2
thanks, hi, dm, reply, ok, great, ll, thanks help, thanks reply, ok thanks, response, check, sure, good, flight
    - 감사

- Topic 3
help, need, need help, account, dm, hi, email, hey, trying, thanks help, number, asap, sent, hello, help account
    - 초반에 언급될만한 단어(일반적)

- Topic 4
thank, dm, sent, reply, sent dm, appreciate, response, flight, great, yes, thank help, okay, hi, ll, did
    - 후반에 언급될만한 단어(일반적)

- Topic 5
just, got, just got, just want, want, sent, just sent, dm, bought, know, wanted, just bought, people, ve just, just wanted
    - 'just'

In [37]:
doc_topic = W / (W.sum(axis=1, keepdims=True) + 1e-10)

doc_topic_df = pd.DataFrame(
    doc_topic,
    columns = [f"Topic {i}" for i in range(n_topics)]
)

In [39]:
result_df.columns

Index(['tweet_id', 'author_id', 'inbound', 'created_at', 'text',
       'response_tweet_id', 'in_response_to_tweet_id', 'clean_text',
       'word_count', 'Topic 0', 'Topic 1', 'Topic 2', 'Topic 3', 'Topic 4',
       'Topic 5'],
      dtype='object')

In [43]:
result_df = customer_sample.reset_index(drop=True).copy()
result_df = pd.concat([result_df, doc_topic_df], axis = 1)

result_df = result_df.drop(['tweet_id', 'author_id', 'inbound', 'created_at','response_tweet_id', 'in_response_to_tweet_id', 'text'], axis=1)

result_df

,clean_text,word_count,Topic 0,Topic 1,Topic 2,Topic 3,Topic 4,Topic 5
0,basically for a chat to be opened from call lo...,23,0.723581,0.000000,0.000000,0.110260,0.000000,0.166159
1,ios and watchos no icon for twitter notificati...,21,0.222050,0.000000,0.000000,0.777950,0.000000,0.000000
2,hi there if i buy call of duty wwii on steam t...,22,0.572109,0.018520,0.196535,0.189838,0.022998,0.000000
3,hi why can t i pay my my dstv texts says the o...,15,0.533921,0.000000,0.180232,0.245931,0.039917,0.000000
4,trying to buy my kid nibling a keyboard for an...,23,0.632672,0.000000,0.031936,0.178702,0.009155,0.147536
...,...,...,...,...,...,...,...,...
26609,not sure this is alright lol rubyoulongtime,7,0.265625,0.000000,0.381587,0.050812,0.115524,0.186453
26610,con yo s creo en el buenfin ahora viene el bla...,21,0.897924,0.027719,0.050844,0.000000,0.000000,0.023514
26611,mobile care i need to speak to someone but i w...,19,0.335987,0.147752,0.000000,0.504626,0.011635,0.000000
26612,my iphone isn t letting me update it ain t shi...,13,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26613,hi i ve been contacted about flight being dela...,21,0.726098,0.000000,0.125322,0.027835,0.120745,0.000000

In [47]:
def show_representative_tweets(df, topic_name, n=10):
    topic_docs = df.sort_values(by=topic_name, ascending=False).head(n)

    for idx, row in topic_docs.iterrows():
        print(f"[{idx}] score = {row[topic_name]:.3f}")
        print(row["clean_text"])
        print()

In [48]:
for i in range(n_topics):
    print("=" * 80)
    print(f"Representative tweets for Topic {i}")
    print("=" * 80)
    show_representative_tweets(result_df, f"Topic {i}", n=10)

================================================================================
Representative tweets for Topic 0
================================================================================
[24248] score = 1.000
that was last time for my last order should i use the same link each time

[7294] score = 1.000
fix my phone i m irritated

[19766] score = 1.000
every time i order a phone with you guys it gets lost stop using

[6951] score = 1.000
i ve been awake for less than half an hour and have used my phone for an even shorter time battery is at now fix this

[8117] score = 1.000
is this charge only because it was my first time ordering is this going to be like this all the time

[16884] score = 1.000
and i have the latest software update which is the ios so why is my phone freezing constantly with a new iphone and the latest update every time a new phone comes out are you trying to get consumers to update their plan

[25675] score = 1.000
what concerning is that each and every time i place an app order the store fucks it up and does nothing about it thats what is concerning it s like if you don t wait in line for minutes so you can babysit the making of your food it will be incorrect

[10966] score = 1.000
in real time by that you mean over the phone my order isn t displaying either

[16347] score = 1.000
almost time for take off virginatlantic heathrowtoatlanta thenneworleans nkotbcruise

[7300] score = 1.000
already waisted my time without any output

================================================================================
Representative tweets for Topic 1
================================================================================
[19099] score = 1.000
scripted customer service is not customer service and every other company

[18213] score = 1.000
week since indicted someone would get back to me momentarily dreadful customer service

[1975] score = 1.000
the customer service received from o insure has been terrible never again will i use this service

[19049] score = 1.000
he needs a lesson in customer service

[18714] score = 1.000
potentially some of the least customer focused customer service i have ever encountered smh

[19127] score = 1.000
your customer service is a joke

[1159] score = 1.000
still no service for me

[12721] score = 1.000
how about y all find us some service

[8878] score = 1.000
what s the next service from hayes to hanwell please

[14029] score = 1.000
what service are you on

================================================================================
Representative tweets for Topic 2
================================================================================
[8653] score = 1.000
thanks you for respon miza

[22377] score = 1.000
thanks teresa i will do

[11900] score = 1.000
thanks everything seems to be back now

[24670] score = 1.000
it s irrelevant so no thanks

[12682] score = 1.000
it has appeared now thanks

[8224] score = 1.000
thanks it s back up

[20055] score = 1.000
thanks have already done that

[4640] score = 1.000
either dunstable or luton bramingham thanks

[5738] score = 1.000
thanks i have dmd you

[15569] score = 1.000
i see i see thanks

================================================================================
Representative tweets for Topic 3
================================================================================
[15262] score = 1.000
locutus but how can you help

[22140] score = 1.000
you are no help at all

[8705] score = 1.000
can you help with this please

[9538] score = 1.000
is there anything you can do to help

[20130] score = 1.000
can i have someone help

[14637] score = 1.000
same here tommy can i have some help too

[25325] score = 1.000
done may you help me now

[7856] score = 1.000
hei can i get some help please

[12397] score = 1.000
i m being verbally abused please help

[11774] score = 1.000
please help me what i should do

================================================================================
Representative tweets for Topic 4
================================================================================
[13143] score = 1.000
it was very enjoyable thank you

[23804] score = 1.000
i have done thank you

[5692] score = 1.000
i see it now thank you

[7609] score = 1.000
thank you for the repsonse

[15983] score = 1.000
thank you i have done that

[14642] score = 1.000
we made it thank you

[19976] score = 1.000
thank you it s a coaxile cord

[18627] score = 1.000
thank you very much rhys

[13433] score = 1.000
all done thank you so much

[13886] score = 1.000
at last thank you josh

================================================================================
Representative tweets for Topic 5
================================================================================
[11728] score = 1.000
niiiiiceee just hooked mine up

[8047] score = 1.000
so i m just out

[23867] score = 1.000
so it s not just me

[181] score = 1.000
just found this in my raspberries

[20241] score = 1.000
must be joking the one i just had was vile

[21133] score = 1.000
and just have to wait

[18948] score = 1.000
it was just funny it wanted me to be signed into live and i was just made me laughed

[8405] score = 1.000
just to show you what i mean

[23926] score = 1.000
it just turned back on for me

[25569] score = 1.000
that chipotle just fcked my stomach upppp

In [49]:
# 본문을 봐도 일부단어에만 꽂힌 것으로 보이므로 중단

# Conclusion

The extracted topics were often dominated by generic conversational words such as “help”, “service”, and “thanks” rather than clearly separated semantic issue categories. Even representative tweets within the same topic frequently shared only superficial lexical similarities instead of broader discourse structure.

These results suggest that traditional bag-of-words topic modeling methods such as NMF may struggle to capture meaningful semantic organization in short and noisy customer-support tweets. The experiment also highlights the limitations of sparse lexical representations for modeling conversational language.